import React, { useState, useCallback, useRef } from 'react';
import type { WritingDocType, WritingMode, WritingStyle, OutlineItem } from '../../types/cast-types';
import { WRITING_DOC_TYPES, WRITING_STYLES, WRITING_MODES } from '../../types/cast-types';
import { generateWriting, extractOutline, countWords as countWordsUtil } from '../../utils/cast/writing-engine';
import { saveCastMemory, autoSaveCastInteraction } from '../../utils/cast/cast-memory-bridge';
import FileImportExportBar from './FileImportExportBar';
import { castFS } from '../../utils/cast/cast-fs-api';

const WritingAssistant: React.FC = () => {
  const [docType, setDocType] = useState<WritingDocType>('weekly-report');
  const [writingMode, setWritingMode] = useState<WritingMode>('generate');
  const [style, setStyle] = useState<WritingStyle>('formal');
  const [content, setContent] = useState('');
  const [title, setTitle] = useState('');
  const [showPreview, setShowPreview] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [outline, setOutline] = useState<OutlineItem[]>([]);
  const [aiInstruction, setAiInstruction] = useState('');
  const [streamText, setStreamText] = useState('');
  const abortRef = useRef<AbortController | null>(null);

  const selectedTemplate = WRITING_DOC_TYPES.find(t => t.key === docType);
  const stats = content ? countWordsUtil(content) : { chars: 0, words: 0, paragraphs: 0, readTime: 1 };

  const handleDocTypeChange = useCallback((type: WritingDocType) => {
    setDocType(type);
    const template = WRITING_DOC_TYPES.find(t => t.key === type);
    if (template && template.template) {
      setContent(template.template);
      if (!title) setTitle(template.label);
    }
  }, [title]);

  const handleAIGenerate = useCallback(async () => {
    if (!aiInstruction.trim() && writingMode === 'generate') return;
    if (isGenerating) return;

    setIsGenerating(true);
    setStreamText('');
    abortRef.current = new AbortController();

    try {
      const result = await generateWriting(
        {
          mode: writingMode,
          docType,
          style,
          userInstruction: aiInstruction || undefined,
          existingContent: content || undefined
        },
        (chunk) => {
          setStreamText(prev => prev + chunk);
        }
      );

      if (writingMode === 'generate' || writingMode === 'continue') {
        setContent(streamText || result.content);
        if (writingMode === 'generate' && !title) {
          setTitle(selectedTemplate?.label || '');
        }
        if (result.outline?.length) {
          setOutline(result.outline as OutlineItem[]);
        }
      } else if (writingMode === 'polish' || writingMode === 'rewrite-expand' || writingMode === 'rewrite-shrink' || writingMode === 'tone-adjust') {
        setContent(result.content);
      }

      setShowPreview(true);

      autoSaveCastInteraction({
        userMessage: aiInstruction || `${WRITING_DOC_TYPES.find(t => t.key === docType)?.label || ''} - ${writingMode}`,
        aiResponse: content.slice(0, 200) + (content.length > 200 ? '...' : ''),
        panel: 'writing',
        actionType: writingMode
      }).catch(() => {});
    } catch (error: any) {
      console.error('[WritingAssistant] AI generation failed:', error);
      setContent(prev => prev + `\n\n❌ 生成失败: ${error.message}`);
    } finally {
      setIsGenerating(false);
      abortRef.current = null;
    }
  }, [writingMode, docType, style, aiInstruction, content, title, selectedTemplate, isGenerating]);

  const handleStopGeneration = useCallback(() => {
    if (abortRef.current) {
      abortRef.current.abort();
      setIsGenerating(false);
    }
  }, []);

  const handleExtractOutline = useCallback(() => {
    if (!content.trim()) return;
    const extracted = extractOutline(content);
    setOutline(extracted.map((item, i) => ({ ...item, id: `outline-${i}` })));
  }, [content]);

  const handleExportDoc = useCallback(() => {
    if (!content.trim() || !title.trim()) return;
    const exportName = `${title || 'document'}.md`;
    const header = `# ${title}\n\n> Generated by CodeCast Writing Assistant\n\n---\n\n`;
    castFS.exportAsFile(header + content, exportName, 'text/markdown').catch(console.error);
  }, [content, title]);

  const simpleMarkdownRender = (text: string): string => {
    return text
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^# (.*$)/gim, '<h1>$1</h1>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/^> (.*$)/gim, '<blockquote>$1</blockquote>')
      .replace(/^- (.*$)/gim, '<li>$1</li>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br/>');
  };

  return (
    <div className="cast-panel-container">
      <div className="cast-toolbar">
        <div className="cast-toolbar-group">
          <span className="cast-tag" style={{ background: 'rgba(245,158,11,0.12)', color: '#f59e0b' }}>
            📝 文档
          </span>
          <select className="cast-toolbar-select" value={docType} onChange={(e) => handleDocTypeChange(e.target.value as WritingDocType)}>
            {WRITING_DOC_TYPES.map(t => (
              <option key={t.key} value={t.key}>{t.icon} {t.label}</option>
            ))}
          </select>
        </div>

        <div className="cast-toolbar-divider" />

        <div className="cast-toolbar-group">
          <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>模式:</span>
          {WRITING_MODES.map(m => (
            <button key={m.key} className={`cast-toolbar-btn ${writingMode === m.key ? 'active' : ''}`} onClick={() => setWritingMode(m.key)} title={m.promptHint}>
              {m.icon} {m.label}
            </button>
          ))}
        </div>

        <div className="cast-toolbar-divider" />

        <div className="cast-toolbar-group">
          <select className="cast-toolbar-select" value={style} onChange={(e) => setStyle(e.target.value as WritingStyle)}>
            {WRITING_STYLES.map(s => (<option key={s.key} value={s.key}>{s.label}</option>))}
          </select>

          <button className={`cast-toolbar-btn active`} onClick={handleAIGenerate} disabled={isGenerating}>
            {isGenerating ? '⏳ 生成中...' : `✨ AI${WRITING_MODES.find(m => m.key === writingMode)?.label || '生成'}`}
          </button>
          {isGenerating && (
            <button className="cast-toolbar-btn" onClick={handleStopGeneration} style={{ borderColor: '#ef4444', color: '#ef4444' }}>
              ⏹ 停止
            </button>
          )}
          <button className="cast-toolbar-btn" onClick={handleExtractOutline}>📑 提纲</button>
          <button className={`cast-toolbar-btn ${showPreview ? 'active' : ''}`} onClick={() => setShowPreview(!showPreview)}>
            {showPreview ? '👁 预览' : '✏️ 编辑'}
          </button>
          <FileImportExportBar mode="export" onExport={handleExportDoc} exportFilename={`${title || 'document'}.md`} exportContent={content} compact />
        </div>
      </div>

      {(writingMode !== 'generate' || isGenerating) && (
        <div style={{ padding: '8px 16px', borderBottom: '1px solid var(--border-color)', display: 'flex', gap: 8, alignItems: 'center' }}>
          <input
            type="text"
            value={aiInstruction}
            onChange={(e) => setAiInstruction(e.target.value)}
            placeholder={
              writingMode === 'generate' ? '描述你想写的内容...' :
              writingMode === 'continue' ? '续写方向（留空则自动续写）...' :
              writingMode === 'polish' ? '润色要求（如：更正式/更简洁）...' :
              writingMode === 'rewrite-expand' ? '扩写要求...' :
              writingMode === 'rewrite-shrink' ? '精简目标长度...' :
              '目标语气风格...'
            }
            style={{
              flex: 1,
              padding: '6px 12px',
              border: '1px solid var(--border-color)',
              background: 'var(--bg-secondary)',
              color: 'var(--text-primary)',
              borderRadius: 6,
              fontSize: 12,
              outline: 'none'
            }}
            onKeyDown={(e) => e.key === 'Enter' && handleAIGenerate()}
          />
        </div>
      )}

      <div className="cast-stat-bar">
        <span className="cast-stat-item">📏 <span className="cast-stat-value">{stats.words}</span> 字</span>
        <span className="cast-stat-item">📝 <span className="cast-stat-value">{stats.chars}</span> 字符</span>
        <span className="cast-stat-item">⏱ 约 <span className="cast-stat-value">{stats.readTime}</span> 分钟阅读</span>
        <span className="cast-stat-item" style={{ marginLeft: 'auto' }}>
          类型: <span className="cast-stat-value" style={{ color: '#f59e0b' }}>{selectedTemplate?.icon} {selectedTemplate?.label}</span>
        </span>
        {outline.length > 0 && (
          <span className="cast-stat-item cast-tag-purple">📑 {outline.length} 个章节</span>
        )}
      </div>

      {outline.length > 0 && showPreview && (
        <div style={{
          padding: '8px 16px',
          borderBottom: '1px solid var(--border-color)',
          display: 'flex',
          gap: 10,
          overflowX: 'auto',
          background: 'rgba(139,92,246,0.04)'
        }}>
          {outline.map((item, i) => (
            <button
              key={i}
              style={{
                padding: '4px 10px',
                border: '1px solid rgba(139,92,246,0.25)',
                background: item.level <= 2 ? 'rgba(139,92,246,0.1)' : 'transparent',
                color: item.level <= 2 ? '#c084fc' : 'var(--text-muted)',
                borderRadius: 4,
                fontSize: item.level <= 2 ? 12 : 11,
                fontWeight: item.level <= 2 ? 600 : 400,
                whiteSpace: 'nowrap',
                cursor: 'pointer'
              }}
            >
              {'　'.repeat(item.level - 1)}{item.title}
            </button>
          ))}
        </div>
      )}

      {!showPreview || isGenerating ? (
        <div className="cast-editor-area" style={{ height: 'calc(100% - 90px)', position: 'relative' }}>
          {writingMode === 'generate' && !isGenerating && (
            <div style={{ padding: '16px', borderBottom: '1px solid var(--border-color)' }}>
              <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="文档标题..." style={{
                width: '100%', border: 'none', background: 'transparent', color: 'var(--text-primary)', fontSize: 20, fontWeight: 700, outline: 'none', paddingBottom: 8
              }} />
            </div>
          )}

          {isGenerating && streamText && !content ? (
            <div className="cast-preview-area" style={{ padding: '14px' }} dangerouslySetInnerHTML={{
              __html: `<div>${simpleMarkdownRender(streamText)}<span style="animation: blink 1s infinite">▊</span></div>`
            }} />
          ) : (
            <textarea className="cast-editor-textarea" value={isGenerating && streamText ? streamText : content} onChange={(e) => setContent(e.target.value)} placeholder={
              writingMode === 'generate' ? '开始写作...（支持 Markdown 格式）' :
              writingMode === 'continue' ? '输入已有内容，AI 将续写...' :
              writingMode === 'polish' ? '粘贴需要润色的文本...' : '输入内容...'
            } />
          )}
        </div>
      ) : (
        <div className="cast-preview-area" dangerouslySetInnerHTML={{
          __html: content ? `<div>${simpleMarkdownRender(content)}</div>` : '<p style="color:var(--text-muted);text-align:center;padding-top:60px;">预览区域 - 点击 "AI生成" 开始创作，或直接编辑内容</p>'
        }} />
      )}
    </div>
  );
};

export default React.memo(WritingAssistant);
