// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAllowedDomain(arg1:string):Promise<void>;

export function AddBlockedDomain(arg1:string):Promise<void>;

export function AddEnvVar(arg1:string,arg2:string):Promise<void>;

export function AddMCPServer(arg1:string,arg2:string):Promise<main.MCPServer>;

export function AddMCPServerStdio(arg1:string,arg2:string,arg3:Array<string>):Promise<main.MCPServer>;

export function AddProject(arg1:string):Promise<main.Project>;

export function AddSlashCommand(arg1:string,arg2:string,arg3:string):Promise<main.SlashCommand>;

export function ArchiveSession(arg1:string):Promise<void>;

export function CancelAgent(arg1:string):Promise<void>;

export function CancelRequest():Promise<void>;

export function CancelSessionAgents(arg1:string):Promise<void>;

export function CancelSessionRequest(arg1:string):Promise<void>;

export function CheckSeleniumInstalled():Promise<Record<string, any>>;

export function ClearBrowserData():Promise<void>;

export function ClearMemory():Promise<void>;

export function ConfirmGitCommit(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string):Promise<main.Session>;

export function CreateSkill(arg1:string,arg2:string,arg3:string):Promise<main.Skill>;

export function CreateTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Task>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DispatchAgents(arg1:string):Promise<Array<string>>;

export function ExecuteCommand(arg1:string,arg2:number):Promise<string>;

export function ExtractSummaryAsync(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAgentDetail(arg1:string):Promise<main.SubAgent>;

export function GetAgents(arg1:string):Promise<Array<main.SubAgent>>;

export function GetArchivedSessions():Promise<Array<main.Session>>;

export function GetAvailableEditors():Promise<Array<main.EditorInfo>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetCurrentProject():Promise<main.Project>;

export function GetDomainRules():Promise<Record<string, any>>;

export function GetEnvVars():Promise<Array<main.EnvVar>>;

export function GetGitStatus():Promise<Record<string, any>>;

export function GetMCPStatus():Promise<Array<Record<string, any>>>;

export function GetMemoryStats():Promise<Record<string, any>>;

export function GetNoProjectMode():Promise<boolean>;

export function GetPlatform():Promise<string>;

export function GetPopoutState():Promise<Record<string, any>>;

export function GetPreferredEditor():Promise<string>;

export function GetProjects():Promise<Array<main.Project>>;

export function GetSession(arg1:string):Promise<main.Session>;

export function GetSessions():Promise<Array<main.Session>>;

export function GetSettings():Promise<main.Settings>;

export function GetSkills():Promise<Array<main.Skill>>;

export function GetSlashCommands():Promise<Array<main.SlashCommand>>;

export function GetTasks():Promise<Array<main.Task>>;

export function GetWorkspaceFiles(arg1:string):Promise<Array<main.FileEntry>>;

export function ImportSkill(arg1:string):Promise<main.Skill>;

export function IsDomainBlocked(arg1:string):Promise<boolean>;

export function ListFiles(arg1:string):Promise<Array<string>>;

export function NotifyAIQuestion(arg1:string):Promise<void>;

export function NotifyPermissionNeeded(arg1:string):Promise<void>;

export function OpenInEditor(arg1:string):Promise<void>;

export function PopoutWindow():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RemoveAllowedDomain(arg1:string):Promise<void>;

export function RemoveBlockedDomain(arg1:string):Promise<void>;

export function RemoveEnvVar(arg1:string):Promise<void>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function RemoveSlashCommand(arg1:string):Promise<void>;

export function ResetMemory():Promise<void>;

export function RunTaskNow(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectMultipleFiles():Promise<Array<string>>;

export function SendMessage(arg1:string,arg2:string):Promise<Array<main.Message>>;

export function SendMessageEx(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<Array<main.Message>>;

export function SendNotification(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAPIKey(arg1:string):Promise<string>;

export function SetCurrentProject(arg1:string):Promise<void>;

export function SetNoProjectMode(arg1:boolean):Promise<void>;

export function SetPreferredEditor(arg1:string):Promise<void>;

export function StartTaskScheduler(arg1:any):Promise<any>;

export function TestMCPServerConnection(arg1:string):Promise<Record<string, any>>;

export function ToggleMCPServer(arg1:string,arg2:boolean):Promise<void>;

export function ToggleTask(arg1:string,arg2:boolean):Promise<void>;

export function UnarchiveSession(arg1:string):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;

export function UpdateSkill(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateSlashCommand(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowSetAlwaysOnTop(arg1:boolean):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
