// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';
import {tools} from '../models';

export function AddAllowedDomain(arg1:string):Promise<void>;

export function AddBlockedDomain(arg1:string):Promise<void>;

export function AddEnvVar(arg1:string,arg2:string):Promise<void>;

export function AddModelConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:boolean):Promise<main.ModelConfigItem>;

export function AddProject(arg1:string):Promise<main.Project>;

export function AddSlashCommand(arg1:string,arg2:string,arg3:string):Promise<main.SlashCommand>;

export function ArchiveSession(arg1:string):Promise<void>;

export function BatchDeleteSessions(arg1:Array<string>):Promise<Array<string>>;

export function CancelAgent(arg1:string):Promise<void>;

export function CancelRequest():Promise<void>;

export function CancelSessionAgents(arg1:string):Promise<void>;

export function CancelSessionRequest(arg1:string):Promise<void>;

export function CheckAntivirusCompatibility():Promise<Record<string, any>>;

export function CheckEnvironment():Promise<main.EnvCheckReport>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CheckSeleniumInstalled():Promise<Record<string, any>>;

export function ClearBrowserData():Promise<void>;

export function ConfirmGitCommit(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string,arg3:string):Promise<main.Session>;

export function CreateSkill(arg1:string,arg2:string,arg3:string):Promise<main.Skill>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DispatchAgents(arg1:string):Promise<Array<string>>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function ExecuteCommand(arg1:string,arg2:number):Promise<string>;

export function ExportSession(arg1:string,arg2:string):Promise<string>;

export function FixEnvironmentIssue(arg1:string):Promise<string>;

export function GetAgentDetail(arg1:string):Promise<main.AgentInfo>;

export function GetAgents(arg1:string):Promise<Array<main.AgentInfo>>;

export function GetAllReleases(arg1:number):Promise<Array<main.UpdateInfo>>;

export function GetArchivedSessions():Promise<Array<main.Session>>;

export function GetAvailableEditors():Promise<Array<main.EditorInfo>>;

export function GetChangelog(arg1:string,arg2:string,arg3:string):Promise<main.Changelog>;

export function GetConfig():Promise<Record<string, any>>;

export function GetCurrentProject():Promise<main.Project>;

export function GetCurrentVersion():Promise<string>;

export function GetDomainRules():Promise<Record<string, any>>;

export function GetEnvVars():Promise<Array<main.EnvVar>>;

export function GetGitStatus():Promise<Record<string, any>>;

export function GetKeyRotationInfo():Promise<Record<string, any>>;

export function GetModelConfigs():Promise<Array<main.ModelConfigItem>>;

export function GetNoProjectMode():Promise<boolean>;

export function GetPlatform():Promise<string>;

export function GetPopoutState():Promise<Record<string, any>>;

export function GetPreferredEditor():Promise<string>;

export function GetProjects():Promise<Array<main.Project>>;

export function GetProviderModels(arg1:string):Promise<Array<string>>;

export function GetProviders():Promise<Array<main.ProviderPreset>>;

export function GetSecurityStatus():Promise<main.SecurityStatus>;

export function GetSession(arg1:string):Promise<main.Session>;

export function GetSessions():Promise<Array<main.Session>>;

export function GetSessionsByMode(arg1:string):Promise<Array<main.Session>>;

export function GetSettings():Promise<main.Settings>;

export function GetSkills():Promise<Array<main.Skill>>;

export function GetSlashCommands():Promise<Array<main.SlashCommand>>;

export function GetToolCatalog():Promise<Array<main.ToolCatalogItem>>;

export function GetToolHistory(arg1:string,arg2:number):Promise<Array<main.CastToolInvocation>>;

export function GetUpdateHistory():Promise<Array<main.UpdateRecord>>;

export function GetWorkspaceFiles(arg1:string):Promise<Array<string>>;

export function ImportSkill(arg1:string):Promise<main.Skill>;

export function InvokeCastTool(arg1:string,arg2:string):Promise<string>;

export function IsDomainBlocked(arg1:string):Promise<boolean>;

export function ListFiles(arg1:string):Promise<Array<string>>;

export function NotifyAIQuestion(arg1:string):Promise<void>;

export function NotifyEnvironmentIssue(arg1:string,arg2:string,arg3:string):Promise<void>;

export function NotifyLongRunning(arg1:string,arg2:time.Duration):Promise<void>;

export function NotifyMemoryFull(arg1:string,arg2:number):Promise<void>;

export function NotifyPermissionNeeded(arg1:string):Promise<void>;

export function NotifySecurityAlert(arg1:string,arg2:string):Promise<void>;

export function NotifySessionComplete(arg1:string):Promise<void>;

export function NotifyTaskCompleted(arg1:string,arg2:string,arg3:string):Promise<void>;

export function NotifyUpdateAvailable(arg1:string):Promise<void>;

export function OpenDownloadedFile(arg1:string):Promise<void>;

export function OpenInEditor(arg1:string):Promise<void>;

export function OpenReleasePage():Promise<void>;

export function PopoutWindow():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RegisterCastTools(arg1:tools.Registry):Promise<void>;

export function RemoveAllowedDomain(arg1:string):Promise<void>;

export function RemoveBlockedDomain(arg1:string):Promise<void>;

export function RemoveEnvVar(arg1:string):Promise<void>;

export function RemoveModelConfig(arg1:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function RemoveSlashCommand(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResolveCheckpoint(arg1:string,arg2:boolean):Promise<void>;

export function RotateEncryptionKey():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SaveUpdateRecord(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function SearchSessions(arg1:string):Promise<Array<main.Session>>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectMultipleFiles():Promise<Array<string>>;

export function SendMessage(arg1:string,arg2:string):Promise<Array<main.Message>>;

export function SendMessageEx(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.Message>>;

export function SendNotification(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAPIKey(arg1:string):Promise<string>;

export function SetCastApp():Promise<void>;

export function SetCurrentProject(arg1:string):Promise<void>;

export function SetNoProjectMode(arg1:boolean):Promise<void>;

export function SetPreferredEditor(arg1:string):Promise<void>;

export function SilentDownload(arg1:string):Promise<void>;

export function ToggleModelConfig(arg1:string,arg2:boolean):Promise<void>;

export function UnarchiveSession(arg1:string):Promise<void>;

export function UpdateModelConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number,arg9:boolean):Promise<void>;

export function UpdateProjectInstructions(arg1:string,arg2:string):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;

export function UpdateSkill(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateSlashCommand(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowSetAlwaysOnTop(arg1:boolean):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
