// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllowedDomain(arg1) {
  return window['go']['main']['App']['AddAllowedDomain'](arg1);
}

export function AddBlockedDomain(arg1) {
  return window['go']['main']['App']['AddBlockedDomain'](arg1);
}

export function AddEnvVar(arg1, arg2) {
  return window['go']['main']['App']['AddEnvVar'](arg1, arg2);
}

export function AddModelConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddModelConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AddSlashCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSlashCommand'](arg1, arg2, arg3);
}

export function ArchiveSession(arg1) {
  return window['go']['main']['App']['ArchiveSession'](arg1);
}

export function BatchDeleteSessions(arg1) {
  return window['go']['main']['App']['BatchDeleteSessions'](arg1);
}

export function CancelAgent(arg1) {
  return window['go']['main']['App']['CancelAgent'](arg1);
}

export function CancelRequest() {
  return window['go']['main']['App']['CancelRequest']();
}

export function CancelSessionAgents(arg1) {
  return window['go']['main']['App']['CancelSessionAgents'](arg1);
}

export function CancelSessionRequest(arg1) {
  return window['go']['main']['App']['CancelSessionRequest'](arg1);
}

export function CheckAntivirusCompatibility() {
  return window['go']['main']['App']['CheckAntivirusCompatibility']();
}

export function CheckEnvironment() {
  return window['go']['main']['App']['CheckEnvironment']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckSeleniumInstalled() {
  return window['go']['main']['App']['CheckSeleniumInstalled']();
}

export function ClearBrowserData() {
  return window['go']['main']['App']['ClearBrowserData']();
}

export function ClearCompletionCache() {
  return window['go']['main']['App']['ClearCompletionCache']();
}

export function ConfirmGitCommit(arg1) {
  return window['go']['main']['App']['ConfirmGitCommit'](arg1);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3);
}

export function CreateSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSkill'](arg1, arg2, arg3);
}

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DispatchAgents(arg1) {
  return window['go']['main']['App']['DispatchAgents'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExportSession(arg1, arg2) {
  return window['go']['main']['App']['ExportSession'](arg1, arg2);
}

export function FixEnvironmentIssue(arg1) {
  return window['go']['main']['App']['FixEnvironmentIssue'](arg1);
}

export function GetAgentDetail(arg1) {
  return window['go']['main']['App']['GetAgentDetail'](arg1);
}

export function GetAgents(arg1) {
  return window['go']['main']['App']['GetAgents'](arg1);
}

export function GetAllReleases(arg1) {
  return window['go']['main']['App']['GetAllReleases'](arg1);
}

export function GetArchivedSessions() {
  return window['go']['main']['App']['GetArchivedSessions']();
}

export function GetAvailableEditors() {
  return window['go']['main']['App']['GetAvailableEditors']();
}

export function GetChangelog(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetChangelog'](arg1, arg2, arg3);
}

export function GetCodeCompletions(arg1) {
  return window['go']['main']['App']['GetCodeCompletions'](arg1);
}

export function GetCompletionStats() {
  return window['go']['main']['App']['GetCompletionStats']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentProject() {
  return window['go']['main']['App']['GetCurrentProject']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDomainRules() {
  return window['go']['main']['App']['GetDomainRules']();
}

export function GetEnvVars() {
  return window['go']['main']['App']['GetEnvVars']();
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetKeyRotationInfo() {
  return window['go']['main']['App']['GetKeyRotationInfo']();
}

export function GetModelConfigs() {
  return window['go']['main']['App']['GetModelConfigs']();
}

export function GetNoProjectMode() {
  return window['go']['main']['App']['GetNoProjectMode']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetPopoutState() {
  return window['go']['main']['App']['GetPopoutState']();
}

export function GetPreferredEditor() {
  return window['go']['main']['App']['GetPreferredEditor']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetProviderModels(arg1) {
  return window['go']['main']['App']['GetProviderModels'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetSecurityStatus() {
  return window['go']['main']['App']['GetSecurityStatus']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSessionsByMode(arg1) {
  return window['go']['main']['App']['GetSessionsByMode'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetSlashCommands() {
  return window['go']['main']['App']['GetSlashCommands']();
}

export function GetTaskStats() {
  return window['go']['main']['App']['GetTaskStats']();
}

export function GetTaskTemplates() {
  return window['go']['main']['App']['GetTaskTemplates']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetUpdateHistory() {
  return window['go']['main']['App']['GetUpdateHistory']();
}

export function GetWorkspaceFiles(arg1) {
  return window['go']['main']['App']['GetWorkspaceFiles'](arg1);
}

export function ImportSkill(arg1) {
  return window['go']['main']['App']['ImportSkill'](arg1);
}

export function IsDomainBlocked(arg1) {
  return window['go']['main']['App']['IsDomainBlocked'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function NotifyAIQuestion(arg1) {
  return window['go']['main']['App']['NotifyAIQuestion'](arg1);
}

export function NotifyEnvironmentIssue(arg1, arg2, arg3) {
  return window['go']['main']['App']['NotifyEnvironmentIssue'](arg1, arg2, arg3);
}

export function NotifyLongRunning(arg1, arg2) {
  return window['go']['main']['App']['NotifyLongRunning'](arg1, arg2);
}

export function NotifyMemoryFull(arg1, arg2) {
  return window['go']['main']['App']['NotifyMemoryFull'](arg1, arg2);
}

export function NotifyPermissionNeeded(arg1) {
  return window['go']['main']['App']['NotifyPermissionNeeded'](arg1);
}

export function NotifySecurityAlert(arg1, arg2) {
  return window['go']['main']['App']['NotifySecurityAlert'](arg1, arg2);
}

export function NotifySessionComplete(arg1) {
  return window['go']['main']['App']['NotifySessionComplete'](arg1);
}

export function NotifyTaskCompleted(arg1, arg2, arg3) {
  return window['go']['main']['App']['NotifyTaskCompleted'](arg1, arg2, arg3);
}

export function NotifyUpdateAvailable(arg1) {
  return window['go']['main']['App']['NotifyUpdateAvailable'](arg1);
}

export function OpenDownloadedFile(arg1) {
  return window['go']['main']['App']['OpenDownloadedFile'](arg1);
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function OpenReleasePage() {
  return window['go']['main']['App']['OpenReleasePage']();
}

export function PauseAllTasks() {
  return window['go']['main']['App']['PauseAllTasks']();
}

export function PopoutWindow() {
  return window['go']['main']['App']['PopoutWindow']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RecordCompletionUsage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RecordCompletionUsage'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoveAllowedDomain(arg1) {
  return window['go']['main']['App']['RemoveAllowedDomain'](arg1);
}

export function RemoveBlockedDomain(arg1) {
  return window['go']['main']['App']['RemoveBlockedDomain'](arg1);
}

export function RemoveEnvVar(arg1) {
  return window['go']['main']['App']['RemoveEnvVar'](arg1);
}

export function RemoveModelConfig(arg1) {
  return window['go']['main']['App']['RemoveModelConfig'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemoveSlashCommand(arg1) {
  return window['go']['main']['App']['RemoveSlashCommand'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ResolveCheckpoint(arg1, arg2) {
  return window['go']['main']['App']['ResolveCheckpoint'](arg1, arg2);
}

export function ResumeAllTasks() {
  return window['go']['main']['App']['ResumeAllTasks']();
}

export function RotateEncryptionKey() {
  return window['go']['main']['App']['RotateEncryptionKey']();
}

export function RunTaskNow(arg1) {
  return window['go']['main']['App']['RunTaskNow'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveUpdateRecord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveUpdateRecord'](arg1, arg2, arg3, arg4);
}

export function SearchSessions(arg1) {
  return window['go']['main']['App']['SearchSessions'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectMultipleFiles() {
  return window['go']['main']['App']['SelectMultipleFiles']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendMessageEx(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessageEx'](arg1, arg2, arg3, arg4);
}

export function SendNotification(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2, arg3);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetCurrentProject(arg1) {
  return window['go']['main']['App']['SetCurrentProject'](arg1);
}

export function SetNoProjectMode(arg1) {
  return window['go']['main']['App']['SetNoProjectMode'](arg1);
}

export function SetPreferredEditor(arg1) {
  return window['go']['main']['App']['SetPreferredEditor'](arg1);
}

export function SilentDownload(arg1) {
  return window['go']['main']['App']['SilentDownload'](arg1);
}

export function StartTaskScheduler(arg1) {
  return window['go']['main']['App']['StartTaskScheduler'](arg1);
}

export function StreamCodeCompletions(arg1) {
  return window['go']['main']['App']['StreamCodeCompletions'](arg1);
}

export function ToggleModelConfig(arg1, arg2) {
  return window['go']['main']['App']['ToggleModelConfig'](arg1, arg2);
}

export function ToggleTask(arg1, arg2) {
  return window['go']['main']['App']['ToggleTask'](arg1, arg2);
}

export function UnarchiveSession(arg1) {
  return window['go']['main']['App']['UnarchiveSession'](arg1);
}

export function UpdateModelConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdateModelConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateProjectInstructions(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectInstructions'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}

export function UpdateSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2, arg3, arg4);
}

export function UpdateSlashCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSlashCommand'](arg1, arg2, arg3, arg4);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4, arg5);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowSetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['WindowSetAlwaysOnTop'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
