// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllowedDomain(arg1) {
  return window['go']['main']['App']['AddAllowedDomain'](arg1);
}

export function AddBlockedDomain(arg1) {
  return window['go']['main']['App']['AddBlockedDomain'](arg1);
}

export function AddEnvVar(arg1, arg2) {
  return window['go']['main']['App']['AddEnvVar'](arg1, arg2);
}

export function AddMCPServer(arg1, arg2) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2);
}

export function AddMCPServerStdio(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMCPServerStdio'](arg1, arg2, arg3);
}

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AddSlashCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSlashCommand'](arg1, arg2, arg3);
}

export function ArchiveSession(arg1) {
  return window['go']['main']['App']['ArchiveSession'](arg1);
}

export function CancelAgent(arg1) {
  return window['go']['main']['App']['CancelAgent'](arg1);
}

export function CancelRequest() {
  return window['go']['main']['App']['CancelRequest']();
}

export function CancelSessionAgents(arg1) {
  return window['go']['main']['App']['CancelSessionAgents'](arg1);
}

export function CancelSessionRequest(arg1) {
  return window['go']['main']['App']['CancelSessionRequest'](arg1);
}

export function CheckSeleniumInstalled() {
  return window['go']['main']['App']['CheckSeleniumInstalled']();
}

export function ClearBrowserData() {
  return window['go']['main']['App']['ClearBrowserData']();
}

export function ClearMemory() {
  return window['go']['main']['App']['ClearMemory']();
}

export function ConfirmGitCommit(arg1) {
  return window['go']['main']['App']['ConfirmGitCommit'](arg1);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3);
}

export function CreateSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSkill'](arg1, arg2, arg3);
}

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DispatchAgents(arg1) {
  return window['go']['main']['App']['DispatchAgents'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExtractSummaryAsync(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractSummaryAsync'](arg1, arg2, arg3);
}

export function GetAgentDetail(arg1) {
  return window['go']['main']['App']['GetAgentDetail'](arg1);
}

export function GetAgents(arg1) {
  return window['go']['main']['App']['GetAgents'](arg1);
}

export function GetArchivedSessions() {
  return window['go']['main']['App']['GetArchivedSessions']();
}

export function GetAvailableEditors() {
  return window['go']['main']['App']['GetAvailableEditors']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentProject() {
  return window['go']['main']['App']['GetCurrentProject']();
}

export function GetDomainRules() {
  return window['go']['main']['App']['GetDomainRules']();
}

export function GetEnvVars() {
  return window['go']['main']['App']['GetEnvVars']();
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetNoProjectMode() {
  return window['go']['main']['App']['GetNoProjectMode']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetPopoutState() {
  return window['go']['main']['App']['GetPopoutState']();
}

export function GetPreferredEditor() {
  return window['go']['main']['App']['GetPreferredEditor']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetSlashCommands() {
  return window['go']['main']['App']['GetSlashCommands']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetWorkspaceFiles(arg1) {
  return window['go']['main']['App']['GetWorkspaceFiles'](arg1);
}

export function ImportSkill(arg1) {
  return window['go']['main']['App']['ImportSkill'](arg1);
}

export function IsDomainBlocked(arg1) {
  return window['go']['main']['App']['IsDomainBlocked'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function NotifyAIQuestion(arg1) {
  return window['go']['main']['App']['NotifyAIQuestion'](arg1);
}

export function NotifyPermissionNeeded(arg1) {
  return window['go']['main']['App']['NotifyPermissionNeeded'](arg1);
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function PopoutWindow() {
  return window['go']['main']['App']['PopoutWindow']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RemoveAllowedDomain(arg1) {
  return window['go']['main']['App']['RemoveAllowedDomain'](arg1);
}

export function RemoveBlockedDomain(arg1) {
  return window['go']['main']['App']['RemoveBlockedDomain'](arg1);
}

export function RemoveEnvVar(arg1) {
  return window['go']['main']['App']['RemoveEnvVar'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemoveSlashCommand(arg1) {
  return window['go']['main']['App']['RemoveSlashCommand'](arg1);
}

export function ResetMemory() {
  return window['go']['main']['App']['ResetMemory']();
}

export function RunTaskNow(arg1) {
  return window['go']['main']['App']['RunTaskNow'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectMultipleFiles() {
  return window['go']['main']['App']['SelectMultipleFiles']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendMessageEx(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessageEx'](arg1, arg2, arg3, arg4);
}

export function SendNotification(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2, arg3);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetCurrentProject(arg1) {
  return window['go']['main']['App']['SetCurrentProject'](arg1);
}

export function SetNoProjectMode(arg1) {
  return window['go']['main']['App']['SetNoProjectMode'](arg1);
}

export function SetPreferredEditor(arg1) {
  return window['go']['main']['App']['SetPreferredEditor'](arg1);
}

export function StartTaskScheduler(arg1) {
  return window['go']['main']['App']['StartTaskScheduler'](arg1);
}

export function TestMCPServerConnection(arg1) {
  return window['go']['main']['App']['TestMCPServerConnection'](arg1);
}

export function ToggleMCPServer(arg1, arg2) {
  return window['go']['main']['App']['ToggleMCPServer'](arg1, arg2);
}

export function ToggleTask(arg1, arg2) {
  return window['go']['main']['App']['ToggleTask'](arg1, arg2);
}

export function UnarchiveSession(arg1) {
  return window['go']['main']['App']['UnarchiveSession'](arg1);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}

export function UpdateSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2, arg3, arg4);
}

export function UpdateSlashCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSlashCommand'](arg1, arg2, arg3, arg4);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowSetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['WindowSetAlwaysOnTop'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
