// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllowedDomain(arg1) {
  return window['go']['main']['App']['AddAllowedDomain'](arg1);
}

export function AddBlockedDomain(arg1) {
  return window['go']['main']['App']['AddBlockedDomain'](arg1);
}

export function AddEnvVar(arg1, arg2) {
  return window['go']['main']['App']['AddEnvVar'](arg1, arg2);
}

export function AddMCPServer(arg1, arg2) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2);
}

export function AddMCPServerStdio(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMCPServerStdio'](arg1, arg2, arg3);
}

export function AddModelConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddModelConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AddSlashCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSlashCommand'](arg1, arg2, arg3);
}

export function AnalyzeImage(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeImage'](arg1, arg2);
}

export function ArchiveSession(arg1) {
  return window['go']['main']['App']['ArchiveSession'](arg1);
}

export function BatchDeleteSessions(arg1) {
  return window['go']['main']['App']['BatchDeleteSessions'](arg1);
}

export function BroadcastMessage(arg1) {
  return window['go']['main']['App']['BroadcastMessage'](arg1);
}

export function CancelAgent(arg1) {
  return window['go']['main']['App']['CancelAgent'](arg1);
}

export function CancelRequest() {
  return window['go']['main']['App']['CancelRequest']();
}

export function CancelSessionAgents(arg1) {
  return window['go']['main']['App']['CancelSessionAgents'](arg1);
}

export function CancelSessionRequest(arg1) {
  return window['go']['main']['App']['CancelSessionRequest'](arg1);
}

export function CancelWorkflow(arg1) {
  return window['go']['main']['App']['CancelWorkflow'](arg1);
}

export function CancelWorkflowRun(arg1) {
  return window['go']['main']['App']['CancelWorkflowRun'](arg1);
}

export function CheckAntivirusCompatibility() {
  return window['go']['main']['App']['CheckAntivirusCompatibility']();
}

export function CheckBudgetExceeded() {
  return window['go']['main']['App']['CheckBudgetExceeded']();
}

export function CheckEnvironment() {
  return window['go']['main']['App']['CheckEnvironment']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckSeleniumInstalled() {
  return window['go']['main']['App']['CheckSeleniumInstalled']();
}

export function ClearBrowserData() {
  return window['go']['main']['App']['ClearBrowserData']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ConfirmGitCommit(arg1) {
  return window['go']['main']['App']['ConfirmGitCommit'](arg1);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3);
}

export function CreateSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSkill'](arg1, arg2, arg3);
}

export function DeleteCheckpoint(arg1) {
  return window['go']['main']['App']['DeleteCheckpoint'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DispatchAgents(arg1) {
  return window['go']['main']['App']['DispatchAgents'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExportSession(arg1, arg2) {
  return window['go']['main']['App']['ExportSession'](arg1, arg2);
}

export function ExportWorkflow(arg1) {
  return window['go']['main']['App']['ExportWorkflow'](arg1);
}

export function ExtractStructured(arg1, arg2) {
  return window['go']['main']['App']['ExtractStructured'](arg1, arg2);
}

export function ExtractStructuredCustom(arg1, arg2) {
  return window['go']['main']['App']['ExtractStructuredCustom'](arg1, arg2);
}

export function FixEnvironmentIssue(arg1) {
  return window['go']['main']['App']['FixEnvironmentIssue'](arg1);
}

export function GetAPMetricsSnapshot() {
  return window['go']['main']['App']['GetAPMetricsSnapshot']();
}

export function GetAgentDetail(arg1) {
  return window['go']['main']['App']['GetAgentDetail'](arg1);
}

export function GetAgentLifecycleStates() {
  return window['go']['main']['App']['GetAgentLifecycleStates']();
}

export function GetAgents(arg1) {
  return window['go']['main']['App']['GetAgents'](arg1);
}

export function GetAllReleases(arg1) {
  return window['go']['main']['App']['GetAllReleases'](arg1);
}

export function GetArchivedSessions() {
  return window['go']['main']['App']['GetArchivedSessions']();
}

export function GetAvailableEditors() {
  return window['go']['main']['App']['GetAvailableEditors']();
}

export function GetBudgetConfig() {
  return window['go']['main']['App']['GetBudgetConfig']();
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetChangelog(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetChangelog'](arg1, arg2, arg3);
}

export function GetCheckpoints(arg1, arg2) {
  return window['go']['main']['App']['GetCheckpoints'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContextWindowConfig() {
  return window['go']['main']['App']['GetContextWindowConfig']();
}

export function GetCostSummary() {
  return window['go']['main']['App']['GetCostSummary']();
}

export function GetCurrentProject() {
  return window['go']['main']['App']['GetCurrentProject']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDomainRules() {
  return window['go']['main']['App']['GetDomainRules']();
}

export function GetEnvVars() {
  return window['go']['main']['App']['GetEnvVars']();
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetGuardrailStatus() {
  return window['go']['main']['App']['GetGuardrailStatus']();
}

export function GetIngestionStatus() {
  return window['go']['main']['App']['GetIngestionStatus']();
}

export function GetKeyRotationInfo() {
  return window['go']['main']['App']['GetKeyRotationInfo']();
}

export function GetLifecycleState() {
  return window['go']['main']['App']['GetLifecycleState']();
}

export function GetMCPServerTools(arg1) {
  return window['go']['main']['App']['GetMCPServerTools'](arg1);
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetMetricsExportPrometheus() {
  return window['go']['main']['App']['GetMetricsExportPrometheus']();
}

export function GetModelConfigs() {
  return window['go']['main']['App']['GetModelConfigs']();
}

export function GetMultimodalCapabilities() {
  return window['go']['main']['App']['GetMultimodalCapabilities']();
}

export function GetNoProjectMode() {
  return window['go']['main']['App']['GetNoProjectMode']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetPluginStatus() {
  return window['go']['main']['App']['GetPluginStatus']();
}

export function GetPopoutState() {
  return window['go']['main']['App']['GetPopoutState']();
}

export function GetPreferredEditor() {
  return window['go']['main']['App']['GetPreferredEditor']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetProviderModels(arg1) {
  return window['go']['main']['App']['GetProviderModels'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetSecurityStatus() {
  return window['go']['main']['App']['GetSecurityStatus']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessionSummary(arg1) {
  return window['go']['main']['App']['GetSessionSummary'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSessionsByMode(arg1) {
  return window['go']['main']['App']['GetSessionsByMode'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetSlashCommands() {
  return window['go']['main']['App']['GetSlashCommands']();
}

export function GetTelemetryStatus() {
  return window['go']['main']['App']['GetTelemetryStatus']();
}

export function GetToolCatalog() {
  return window['go']['main']['App']['GetToolCatalog']();
}

export function GetToolHistory(arg1, arg2) {
  return window['go']['main']['App']['GetToolHistory'](arg1, arg2);
}

export function GetTopicConstraints() {
  return window['go']['main']['App']['GetTopicConstraints']();
}

export function GetUpdateHistory() {
  return window['go']['main']['App']['GetUpdateHistory']();
}

export function GetWorkflowRun(arg1) {
  return window['go']['main']['App']['GetWorkflowRun'](arg1);
}

export function GetWorkflowStatus(arg1) {
  return window['go']['main']['App']['GetWorkflowStatus'](arg1);
}

export function GetWorkspaceFiles(arg1) {
  return window['go']['main']['App']['GetWorkspaceFiles'](arg1);
}

export function ImportSkill(arg1) {
  return window['go']['main']['App']['ImportSkill'](arg1);
}

export function IngestDirectory(arg1, arg2) {
  return window['go']['main']['App']['IngestDirectory'](arg1, arg2);
}

export function InvalidateCacheKey(arg1) {
  return window['go']['main']['App']['InvalidateCacheKey'](arg1);
}

export function InvokeCastTool(arg1, arg2) {
  return window['go']['main']['App']['InvokeCastTool'](arg1, arg2);
}

export function IsDomainBlocked(arg1) {
  return window['go']['main']['App']['IsDomainBlocked'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function ListWorkflowExecutions() {
  return window['go']['main']['App']['ListWorkflowExecutions']();
}

export function ListWorkflowRuns() {
  return window['go']['main']['App']['ListWorkflowRuns']();
}

export function LoadCheckpoint(arg1) {
  return window['go']['main']['App']['LoadCheckpoint'](arg1);
}

export function LoadPlugin(arg1) {
  return window['go']['main']['App']['LoadPlugin'](arg1);
}

export function NotifyAIQuestion(arg1) {
  return window['go']['main']['App']['NotifyAIQuestion'](arg1);
}

export function NotifyEnvironmentIssue(arg1, arg2, arg3) {
  return window['go']['main']['App']['NotifyEnvironmentIssue'](arg1, arg2, arg3);
}

export function NotifyLongRunning(arg1, arg2) {
  return window['go']['main']['App']['NotifyLongRunning'](arg1, arg2);
}

export function NotifyMemoryFull(arg1, arg2) {
  return window['go']['main']['App']['NotifyMemoryFull'](arg1, arg2);
}

export function NotifyPermissionNeeded(arg1) {
  return window['go']['main']['App']['NotifyPermissionNeeded'](arg1);
}

export function NotifySecurityAlert(arg1, arg2) {
  return window['go']['main']['App']['NotifySecurityAlert'](arg1, arg2);
}

export function NotifySessionComplete(arg1) {
  return window['go']['main']['App']['NotifySessionComplete'](arg1);
}

export function NotifyTaskCompleted(arg1, arg2, arg3) {
  return window['go']['main']['App']['NotifyTaskCompleted'](arg1, arg2, arg3);
}

export function NotifyUpdateAvailable(arg1) {
  return window['go']['main']['App']['NotifyUpdateAvailable'](arg1);
}

export function OpenDownloadedFile(arg1) {
  return window['go']['main']['App']['OpenDownloadedFile'](arg1);
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function OpenReleasePage() {
  return window['go']['main']['App']['OpenReleasePage']();
}

export function PauseWorkflow(arg1) {
  return window['go']['main']['App']['PauseWorkflow'](arg1);
}

export function PopoutWindow() {
  return window['go']['main']['App']['PopoutWindow']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RegisterCastTools(arg1) {
  return window['go']['main']['App']['RegisterCastTools'](arg1);
}

export function RegisterPluginHandler(arg1, arg2) {
  return window['go']['main']['App']['RegisterPluginHandler'](arg1, arg2);
}

export function RemoveAllowedDomain(arg1) {
  return window['go']['main']['App']['RemoveAllowedDomain'](arg1);
}

export function RemoveBlockedDomain(arg1) {
  return window['go']['main']['App']['RemoveBlockedDomain'](arg1);
}

export function RemoveEnvVar(arg1) {
  return window['go']['main']['App']['RemoveEnvVar'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RemoveModelConfig(arg1) {
  return window['go']['main']['App']['RemoveModelConfig'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemoveSlashCommand(arg1) {
  return window['go']['main']['App']['RemoveSlashCommand'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ResetCostTracker() {
  return window['go']['main']['App']['ResetCostTracker']();
}

export function ResolveCheckpoint(arg1, arg2) {
  return window['go']['main']['App']['ResolveCheckpoint'](arg1, arg2);
}

export function ResumeFromCheckpoint(arg1, arg2) {
  return window['go']['main']['App']['ResumeFromCheckpoint'](arg1, arg2);
}

export function ResumeWorkflow(arg1) {
  return window['go']['main']['App']['ResumeWorkflow'](arg1);
}

export function RotateEncryptionKey() {
  return window['go']['main']['App']['RotateEncryptionKey']();
}

export function RunCodeReviewWorkflow(arg1, arg2) {
  return window['go']['main']['App']['RunCodeReviewWorkflow'](arg1, arg2);
}

export function RunHandoffWorkflow(arg1, arg2) {
  return window['go']['main']['App']['RunHandoffWorkflow'](arg1, arg2);
}

export function RunParallelAnalysis(arg1, arg2) {
  return window['go']['main']['App']['RunParallelAnalysis'](arg1, arg2);
}

export function RunRefactoringWorkflow(arg1, arg2) {
  return window['go']['main']['App']['RunRefactoringWorkflow'](arg1, arg2);
}

export function RunTestPipelineWorkflow(arg1, arg2) {
  return window['go']['main']['App']['RunTestPipelineWorkflow'](arg1, arg2);
}

export function RunWorkflow(arg1, arg2) {
  return window['go']['main']['App']['RunWorkflow'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveUpdateRecord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveUpdateRecord'](arg1, arg2, arg3, arg4);
}

export function SearchSessions(arg1) {
  return window['go']['main']['App']['SearchSessions'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectMultipleFiles() {
  return window['go']['main']['App']['SelectMultipleFiles']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendMessageEx(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessageEx'](arg1, arg2, arg3, arg4);
}

export function SendMessageWithAttachments(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessageWithAttachments'](arg1, arg2, arg3);
}

export function SendNotification(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2, arg3);
}

export function SendPluginMessage(arg1, arg2) {
  return window['go']['main']['App']['SendPluginMessage'](arg1, arg2);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetBudgetConfig(arg1) {
  return window['go']['main']['App']['SetBudgetConfig'](arg1);
}

export function SetBudgetLimit(arg1) {
  return window['go']['main']['App']['SetBudgetLimit'](arg1);
}

export function SetCacheEnabled(arg1) {
  return window['go']['main']['App']['SetCacheEnabled'](arg1);
}

export function SetContextWindowKeepLast(arg1) {
  return window['go']['main']['App']['SetContextWindowKeepLast'](arg1);
}

export function SetCurrentProject(arg1) {
  return window['go']['main']['App']['SetCurrentProject'](arg1);
}

export function SetNoProjectMode(arg1) {
  return window['go']['main']['App']['SetNoProjectMode'](arg1);
}

export function SetPreferredEditor(arg1) {
  return window['go']['main']['App']['SetPreferredEditor'](arg1);
}

export function SetSanitizerStrategy(arg1) {
  return window['go']['main']['App']['SetSanitizerStrategy'](arg1);
}

export function SetTelemetryEndpoint(arg1) {
  return window['go']['main']['App']['SetTelemetryEndpoint'](arg1);
}

export function SilentDownload(arg1) {
  return window['go']['main']['App']['SilentDownload'](arg1);
}

export function StartHTTPTransport(arg1) {
  return window['go']['main']['App']['StartHTTPTransport'](arg1);
}

export function StopHTTPTransport() {
  return window['go']['main']['App']['StopHTTPTransport']();
}

export function TestMCPServerConnection(arg1) {
  return window['go']['main']['App']['TestMCPServerConnection'](arg1);
}

export function ToggleMCPServer(arg1, arg2) {
  return window['go']['main']['App']['ToggleMCPServer'](arg1, arg2);
}

export function ToggleModelConfig(arg1, arg2) {
  return window['go']['main']['App']['ToggleModelConfig'](arg1, arg2);
}

export function ToggleSanitizer(arg1) {
  return window['go']['main']['App']['ToggleSanitizer'](arg1);
}

export function ToggleTelemetry(arg1) {
  return window['go']['main']['App']['ToggleTelemetry'](arg1);
}

export function UnarchiveSession(arg1) {
  return window['go']['main']['App']['UnarchiveSession'](arg1);
}

export function UnloadPlugin(arg1) {
  return window['go']['main']['App']['UnloadPlugin'](arg1);
}

export function UpdateModelConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdateModelConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateProjectInstructions(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectInstructions'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}

export function UpdateSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2, arg3, arg4);
}

export function UpdateSlashCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSlashCommand'](arg1, arg2, arg3, arg4);
}

export function UpdateTopicConstraints(arg1) {
  return window['go']['main']['App']['UpdateTopicConstraints'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowSetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['WindowSetAlwaysOnTop'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
