// Stub for wailsjs/runtime/runtime — auto-generated by Wails at runtime
export function EventsOn() {}
export function EventsOff() {}
export function EventsEmit() {}
export function LogPrint() {}
export function LogTrace() {}
export function LogDebug() {}
export function LogInfo() {}
export function LogWarning() {}
export function LogError() {}
export function LogFatal() {}
export function WindowReload() {}
export function WindowSetSystemDefaultTheme() {}
export function WindowSetLightTheme() {}
export function WindowSetDarkTheme() {}
export function WindowCenter() {}
export function WindowSetTitle() {}
export function WindowFullscreen() {}
export function WindowUnfullscreen() {}
export function WindowIsFullscreen() { return Promise.resolve(false); }
export function WindowSetSize() {}
export function WindowGetSize() { return Promise.resolve({ w: 0, h: 0 }); }
export function WindowSetPosition() {}
export function WindowGetPosition() { return Promise.resolve({ x: 0, y: 0 }); }
export function WindowHide() {}
export function WindowShow() {}
export function WindowMaximise() {}
export function WindowToggleMaximise() {}
export function WindowUnmaximise() {}
export function WindowIsMaximised() { return Promise.resolve(false); }
export function WindowMinimise() {}
export function WindowIsMinimised() { return Promise.resolve(false); }
export function WindowIsNormal() { return Promise.resolve(true); }
export function WindowSetBackgroundColour() {}
export function BrowserOpenURL() {}
export function Environment() { return Promise.resolve({ buildType: 'dev', platform: 'windows' }); }
