// Type declarations for wailsjs/runtime/runtime stub
export function EventsOn(topic: string, cb: any): void;
export function EventsOff(topic: string): void;
export function EventsEmit(topic: string, ...args: any[]): void;
export function LogPrint(message: string): void;
export function LogTrace(message: string): void;
export function LogDebug(message: string): void;
export function LogInfo(message: string): void;
export function LogWarning(message: string): void;
export function LogError(message: string): void;
export function LogFatal(message: string): void;
export function WindowReload(): void;
export function WindowSetSystemDefaultTheme(): void;
export function WindowSetLightTheme(): void;
export function WindowSetDarkTheme(): void;
export function WindowCenter(): void;
export function WindowSetTitle(title: string): void;
export function WindowFullscreen(): void;
export function WindowUnfullscreen(): void;
export function WindowIsFullscreen(): Promise<boolean>;
export function WindowSetSize(width: number, height: number): void;
export function WindowGetSize(): Promise<{ w: number; h: number }>;
export function WindowSetPosition(x: number, y: number): void;
export function WindowGetPosition(): Promise<{ x: number; y: number }>;
export function WindowHide(): void;
export function WindowShow(): void;
export function WindowMaximise(): void;
export function WindowToggleMaximise(): void;
export function WindowUnmaximise(): void;
export function WindowIsMaximised(): Promise<boolean>;
export function WindowMinimise(): void;
export function WindowIsMinimised(): Promise<boolean>;
export function WindowIsNormal(): Promise<boolean>;
export function WindowSetBackgroundColour(r: number, g: number, b: number, a: number): void;
export function BrowserOpenURL(url: string): void;
export function Environment(): Promise<{ buildType: string; platform: string }>;
